repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: trailing-whitespace
        exclude: ^.*/?setup\.py$
      - id: end-of-file-fixer
        exclude: ^.*/?setup\.py$
      - id: debug-statements
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/timothycrosley/isort
    rev: "5.6.4"
    hooks:
      - id: isort
        args: [ "--profile", "black" ]
        additional_dependencies: [ toml ]
        exclude: ^.*/?setup\.py$

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: d6e415450ce274073fffad32c6503ad35a9cacea
    hooks:
      - id: markdownlint
        files: \.(md|mdown|markdown)$
